name: expense_manager_api
description: A simple expense manager API.
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  http: ^1.6.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  sqlite3: ^2.4.2
dev_dependencies:
  test: ^1.31.1
